### ISSUE TITLE
Fix weird boxes after new update.

### ISSUE THREAD

**Issue by Dumbledore-web** [cgsdiscord/deeds-cord#15]
![image](https://user-images.githubusercontent.com/70784752/136881527-72a0ebc3-2b2b-4500-a2d8-880965235f53.png)

**Comment by Richie-exe** [comment]
Is the whole thing supposed to be red or the whole thing supposed to be blue?

if red:
replace (line 208 approx)
```
div.card-content.classes.actions-small-1{
  border-radius: 0px 0px 8px 8px !important;
  background-color: var(--**secondary**) !important;
}
```
with
```
div.card-content.classes.actions-small-1{
  border-radius: 0px 0px 8px 8px !important;
  background-color: var(--**primary**) !important;
}
```

if blue:
replace (line 188 approx)
```
div.list-item{
  background-color: var(--**primary**) !important;
  border-radius: 8px !important;
}
```
with
```
div.list-item{
  background-color: var(--**secondary**) !important;
  border-radius: 8px !important;
}
```

or you can just keep both colours the same

**Comment by Dumbledore-web** [comment]
> Is the whole thing supposed to be red or the whole thing supposed to be blue?
> 
> if red: replace (line 208 approx)
> 
> ```
> div.card-content.classes.actions-small-1{
>   border-radius: 0px 0px 8px 8px !important;
>   background-color: var(--secondary) !important;
> }
> ```
> 
> with
> 
> ```
> div.card-content.classes.actions-small-1{
>   border-radius: 0px 0px 8px 8px !important;
>   background-color: var(--primary) !important;
> }
> ```
> 
> if blue: replace (line 188 approx)
> 
> ```
> div.list-item{
>   background-color: var(--primary) !important;
>   border-radius: 8px !important;
> }
> ```
> 
> with
> 
> ```
> div.list-item{
>   background-color: var(--secondary) !important;
>   border-radius: 8px !important;
> }
> ```
> 
> (doing this one will also change the groups thing on the home page (i think))
> 
> or you can just keep both colours the same

red

**Comment by Dumbledore-web** [comment]
done.
