### ISSUE TITLE
DEEDS Guidelines of Use and Privacy Policy is Hidden

### ISSUE THREAD

**Issue by ARM64-X86** [cgsdiscord/deeds-cord#17]
This is a very important issue, and should be fixed as soon as possible. The extension does not allow the user to view the DEEDS Guidelines of Use and Privacy Policy, and instead, white lines are shown.
<img width="1431" alt="Screen Shot 2021-10-12 at 9 30 30 pm" src="https://user-images.githubusercontent.com/88969535/136939820-0f089e67-d058-4555-a75c-50322a7a4b79.png">

**Comment by Dumbledore-web** [comment]
I will try and fix this right away

**Comment by Dumbledore-web** [comment]
This will be fixed in the next release in a few minutes.

**Comment by Dumbledore-web** [comment]
Fixed in 2.2.0.
