### ISSUE TITLE
News Permissions page does not have any modified colour

### ISSUE THREAD

**Issue by dfmeow** [cgsdiscord/deeds-cord#39]
Issue where popup is not in dark mode
[![image??? lol](https://i.gyazo.com/f8b96aa0a2c57fa3c4684b460114bf27.png)](https://gyazo.com/f8b96aa0a2c57fa3c4684b460114bf27)

**Comment by Richie-exe** [comment]
where to find this?

**Comment by dfmeow** [comment]
- Go to any news article
- click the button next to Permissions (it should be next to where it says who posted it)

**Comment by Richie-exe** [comment]
Solved in https://github.com/cgsdiscord/deeds-cord/pull/51
