### ISSUE TITLE
fix a.exit-off-canvas highlight colour

### ISSUE THREAD

**Issue by traumatram** [cgsdiscord/deeds-cord#55]
a.exit-off-canvas hover transparent

**Comment by Dumbledore-web** [comment]
screenshot

**Comment by Dumbledore-web** [comment]
describe it better

**Comment by traumatram** [comment]
![image](https://user-images.githubusercontent.com/85923335/141218295-1c72eb57-acb5-4e33-9a11-6be620bef8af.png)

**Comment by Dumbledore-web** [comment]
why

**Comment by Dumbledore-web** [comment]
it looks fine
